const allRoles = {
  USER: [
    'view_users',
    'view_skus',
    'view_garantias',
    'register_garantias',
    'identify_garantias',
    'view_qrcodes',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
  SUPER: [
    'view_users',
    'manage_users',
    'delete_users',
    'view_skus',
    'manage_skus',
    'delete_skus',
    'manage_garantias',
    'view_garantias',
    'assign_garantias',
    'register_garantias',
    'control_garantias',
    'identify_garantias',
    'delete_garantias',
    'view_qrcodes',
    'manage_qrcodes',
    'delete_qrcodes',
    'view_prints',
    'manage_prints',
    'delete_prints',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
  ADMIN: [
    'view_users',
    'manage_users',
    'view_skus',
    'manage_skus',
    'delete_skus',
    'manage_garantias',
    'view_garantias',
    'assign_garantias',
    'register_garantias',
    'control_garantias',
    'identify_garantias',
    'delete_garantias',
    'view_qrcodes',
    'manage_qrcodes',
    'delete_qrcodes',
    'view_prints',
    'manage_prints',
    'delete_prints',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
  CARRIER: [
    'view_users',
    'view_skus',
    'manage_skus',
    'delete_skus',
    'view_garantias',
    'identify_garantias',
    'view_qrcodes',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
  SALES: [
    'view_users',
    'view_skus',
    'manage_skus',
    'delete_skus',
    'view_garantias',
    'identify_garantias',
    'view_qrcodes',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
  QA: [
    'view_users',
    'view_skus',
    'manage_skus',
    'view_garantias',
    'assign_garantias',
    'control_garantias',
    'identify_garantias',
    'view_qrcodes',
    'view_prints',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
  MAINTENANCE: [
    'view_users',
    'view_skus',
    'manage_skus',
    'delete_skus',
    'view_garantias',
    'identify_garantias',
    'view_qrcodes',
    'upload_file',
    'refresh_tokens',
    'manage_profile',
    'view_profile',
  ],
};

const enumRoles = {
  ADMIN: 1,
  USER: 2,
  CARRIER: 3,
  SALES: 4,
  QA: 5,
  MAINTENANCE: 6,
  SUPER: 7,
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
  enumRoles,
};
